#!/usr/bin/perl

# --- # meta for dee:
# name: dee
# purpose: delayed tee !
# usage: uniq $file | dee $file
# ---

my $buf = '';
local $/ = "\n";
# -----------------------------------
# -- Options parsing ...
#
my $append = 0;
my $quiet = 0;
my ($exist,$dir,$file,$uniq,$first,$last) = (0,0,0,0,0,0);
while (@ARGV && $ARGV[0] =~ m/^-/)
{
  $_ = shift;
  #/^-(l|r|i|s)(\d+)/ && (eval "\$$1 = \$2", next);
  if (/^--?a(?:ppend)?/) { $append= 1; }
  elsif (/^--?1(?:st)?/) { $first= 1; }
  elsif (/^--?l(?:ast)?/) { $last= 1; }
  elsif (/^--?u(?:niq)?/) { $uniq= 1; }
  elsif (/^--?e(?:xist)?/) { $exist= 1; }
  elsif (/^--?d(?:dir)?/) { $dir= 1; }
  elsif (/^--?f(?:file)?/) { $file= 1; }
  elsif (/^--?q(?:uiet)?/) { $quiet= 1; }
  else { die "Unrecognized switch: $_\n"; }

}
#understand variable=value on the command line...
eval "\$$1='$2'"while $ARGV[0] =~ /^(\w+)=(.*)/ && shift;
# -----------------------------------
# TODO: fist and last option
# -----------------------------------
my %seed = ();
while (<STDIN>) {
  if ($uniq) {
    my $l = $_; chomp($l);
    next if $seen{$l}++;
  }
  if ($exist) {
    my $f = $_; chomp($f);
    $buf .= $_ if (-e $f);
  } elsif ($file) {
    my $f = $_; chomp($f);
    $buf .= $_ if (-f $f);
  } elsif ($dir) {
    my $d = $_; chomp($d);
    $buf .= $_ if (-d $d);
  } else {
     $buf .= $_;
  }
  print unless $quiet;
}
close STDIN;
# -----------------------------------
my $file = $ARGV[0] || '/tmp/dee.log';
local *F;
if ($append) {
   open F,'>>',$file;
} else {
   open F,'>',$file;
}
print F $buf;
close F;
# -----------------------------------
exit $?;

1; # $Source: /my/perl/scripts/dee.pl $


