#!/usr/bin/perl

# --- # meta for uni9
# name: uni9
# details: a uniq (for 733T that doesn't need a sort !
# usage: uni9 $file | more
# ---

my $space = 0;
my %seen = ();
local $/ = "\n";
while (<>) {
   if ($_ =~ /^\s*$/) {
      print "\n" unless $space++ > 0;
   } else {
      $space = 0;
      print $_ unless $seen{$_}++;
   }
}
exit $?;
1; # $Source: /my/perl/scripts/uni9.pl $

