#!/usr/bin/perl

local $/ = undef;
my $buf = <STDIN>;
use YAML::Syck qw(Load Dump);

$buf = "--- \n" . $buf if ($buf !~ m/^---/);
$buf =~ y/\t/ /;
#printf "buf: %s\n",$buf;

my $yml = Load($buf);
#printf "yml: %s\n",Dump($yml);

my $LF = ($#ARGV > 0) ? "\n" : '';
if (@ARGV) {
foreach (@ARGV) {
  my $a = $_;
  $a =~ s/^(\w+)/{$1}/;
  $a =~ s/\.(\w+)/{$1}/g;
  $a = '$yml->'.$a;
  if ($debug) {
  printf "a: %s\n",$a;
  }
  my $ref = eval("ref($a)");
  if ($ref eq '') {
     printf "%s",eval "$a"; 
  } elsif ($ref eq 'ARRAY') {
     printf "%s".$LF,join',',eval("@{$a}");
  } elsif ($ref eq 'HASH') {
     print Dump(eval("$a")),$LF;
  } else {
     printf "ref(%s): %s\n",$_,eval "ref($a)"; 
  }
}
} else {
 printf "%s...\n",YAML::Syck::Dump($yml);
}

exit $?;
1;
